# The main config file for your Jekyll template

# Where things are
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/
  my_tags:
    output: true
    permalink: /blog/tag/:name/
    
# Site settings
title: FodBlog               # used for the html title of every page
desc: >
  Fodmap friendly, human readable, easily executed recipes.

url: http://fodblog.github.io      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: keeeto2000@gmail.com
author: Fodblog
twitter_username: keeeto2000
github_username: fodblog
github_source: jackal

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/articles/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Recent
    url: /articles/
    desc: Real time blog of the recipes
  - title: Food Types
    url: /food_types/
    desc: Stuff we like to eat
  - title: Tags
    url: /tags/
    desc: What goes in
  - title: Recipes
    url: https://fodblog.github.io/blog/tag/recipes/
    desc: Learn about us

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate

# Google services
google_analytics: UA-99249413-1
